version: '3.8'

services:
  client:
    image: mernacr123.azurecr.io/mern-client:latest
    ports:
      - "80:80"
    environment:
      - WEBSITES_PORT=80

  server:
    image: mernacr123.azurecr.io/mern-server:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
