version: '3.8'

services:
  client:
    image: mernacr123.azurecr.io/mern-client:latest
    ports:
      - "80:80"
    environment:
      - WEBSITES_PORT=80
      - NODE_ENV=production
    depends_on:
      - server

  server:
    image: mernacr123.azurecr.io/mern-server:latest
    expose:
      - "5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      # Use Azure CosmosDB or MongoDB Atlas connection string
      - MONGODB_URI=${MONGODB_URI}
      - CORS_ORIGIN=https://mern-app-zafran.azurewebsites.net
