version: '3.8'

services:
  client:
    image: mernacr123.azurecr.io/mern-client:latest
    ports:
      - "80:80"
    environment:
      - WEBSITES_PORT=80
    depends_on:
      - server

  server:
    image: mernacr123.azurecr.io/mern-server:latest
    # Remove external port mapping - only internal communication
    expose:
      - "5000"
    environment:
      - PORT=5000
